# Lecture Week 4 Session 2

## Working with Pandas

***

In this notebook we cover 

**Knowledge on**:

* Data wrangling principles and practices
* Filtering, changing, grouping and joining data
* The pandas package


**Skills on**:

* Data wrangling principles and practices
* Filtering, changing, grouping and joining data
* The pandas package

# Working with pandas

In [1]:
import pandas as pd

In [19]:
#Importing data with pandas is incredibly easy
tweets = pd.read_csv("tweets.csv")

# Alternatively, you can read it directly from Github
git_tweets = pd.read_csv("https://raw.githubusercontent.com/uva-cw-ccs1/2425s2/main/week4/Lecture/tweets.csv")

# Wrangling 101

Get a feeling for your dataset:

In [4]:
# Show the first five rows...
tweets.head()

,source,id,author_id,possibly_sensitive,reply_settings,created_at,conversation_id,public_metrics,referenced_tweets,entities,lang,text,context_annotations,in_reply_to_user_id,attachments,geo,metric_retweet_count,metric_reply_count,metric_like_count,metric_quote_count
0,Twitter for Android,1496434995132575748,1495746927794835457,False,everyone,2022-02-23T10:41:19.000Z,1496434995132575748,"{'retweet_count': 208, 'reply_count': 0, 'like...","[{'type': 'retweeted', 'id': '1489536434054868...","{'mentions': [{'start': 3, 'end': 18, 'usernam...",pt,RT @tatuadoysafado: Gravei meu primeiro conteu...,NaN,NaN,NaN,NaN,208,0,0,0
1,Twitter Web App,1496434990413975557,130796328,False,everyone,2022-02-23T10:41:18.000Z,1496434990413975557,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",NaN,"{'urls': [{'start': 245, 'end': 268, 'url': 'h...",it,Conservazione sostitutiva e messa a norma in a...,"[{'domain': {'id': '66', 'name': 'Interests an...",NaN,NaN,NaN,0,0,0,0
2,Twitter for Android,1496434987666755588,873649157185171467,False,everyone,2022-02-23T10:41:18.000Z,1496434987666755588,"{'retweet_count': 2011, 'reply_count': 0, 'lik...","[{'type': 'retweeted', 'id': '1496205931553730...","{'mentions': [{'start': 3, 'end': 18, 'usernam...",en,RT @Mindfulness_DQ: More prayer. More self-car...,"[{'domain': {'id': '65', 'name': 'Interests an...",NaN,NaN,NaN,2011,0,0,0
3,Twitter for iPhone,1496434984332275715,4405550069,False,everyone,2022-02-23T10:41:17.000Z,1496434984332275715,"{'retweet_count': 4, 'reply_count': 0, 'like_c...","[{'type': 'retweeted', 'id': '1496131686106599...","{'mentions': [{'start': 3, 'end': 13, 'usernam...",en,RT @TechHerNG: Google is rethinking its privac...,"[{'domain': {'id': '46', 'name': 'Brand Catego...",NaN,NaN,NaN,4,0,0,0
4,Twitter for Android,1496434984076419074,849164739880001536,False,everyone,2022-02-23T10:41:17.000Z,1496434984076419074,"{'retweet_count': 64, 'reply_count': 0, 'like_...","[{'type': 'retweeted', 'id': '1496332436799737...","{'mentions': [{'start': 3, 'end': 17, 'usernam...",en,RT @odisha_police: OTP is not only stand for t...,"[{'domain': {'id': '65', 'name': 'Interests an...",NaN,NaN,NaN,64,0,0,0

In [5]:
# ... and the last five rows
tweets.tail()

,source,id,author_id,possibly_sensitive,reply_settings,created_at,conversation_id,public_metrics,referenced_tweets,entities,lang,text,context_annotations,in_reply_to_user_id,attachments,geo,metric_retweet_count,metric_reply_count,metric_like_count,metric_quote_count
1293,Twitter for iPhone,1496424970951569409,56481748,False,everyone,2022-02-23T10:01:29.000Z,1496424970951569409,"{'retweet_count': 2639, 'reply_count': 0, 'lik...","[{'type': 'retweeted', 'id': '1496145104880521...","{'mentions': [{'start': 3, 'end': 16, 'usernam...",en,"RT @WealthInc247: Fall in love with privacy, b...",NaN,NaN,NaN,NaN,2639,0,0,0
1294,TweetDeck,1496424969932541952,1290842099244363776,False,everyone,2022-02-23T10:01:29.000Z,1496424775149035528,"{'retweet_count': 1, 'reply_count': 1, 'like_c...","[{'type': 'replied_to', 'id': '149642477514903...","{'hashtags': [{'start': 144, 'end': 159, 'tag'...",en,The bill contains dangerous provisions such as...,"[{'domain': {'id': '65', 'name': 'Interests an...",1.290842e+18,NaN,NaN,1,1,1,0
1295,Twitter for iPhone,1496424961640128512,1215284173939802112,True,everyone,2022-02-23T10:01:27.000Z,1496424961640128512,"{'retweet_count': 292, 'reply_count': 0, 'like...","[{'type': 'retweeted', 'id': '1495759215054442...","{'urls': [{'start': 87, 'end': 110, 'url': 'ht...",pt,RT @oteuporrete23: Vou mostrar os dias que che...,NaN,NaN,NaN,NaN,292,0,0,0
1296,Twitter for iPhone,1496424961145458691,1172726522446114816,False,everyone,2022-02-23T10:01:27.000Z,1496424961145458691,"{'retweet_count': 19, 'reply_count': 0, 'like_...","[{'type': 'retweeted', 'id': '1496414956426002...","{'mentions': [{'start': 3, 'end': 18, 'usernam...",en,RT @everyoneswhore: She just wants some privac...,NaN,NaN,NaN,NaN,19,0,0,0
1297,Twitter for Android,1496424957420896257,56672287,False,everyone,2022-02-23T10:01:26.000Z,1496378171641454592,"{'retweet_count': 0, 'reply_count': 0, 'like_c...","[{'type': 'replied_to', 'id': '149637817164145...","{'mentions': [{'start': 0, 'end': 13, 'usernam...",en,@virtuexmoir2 Settigns and Privacy &gt; Securi...,"[{'domain': {'id': '65', 'name': 'Interests an...",1.294110e+18,NaN,NaN,0,0,0,0

In [6]:
# Get a high-level summary of your data
tweets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1298 entries, 0 to 1297
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   source                1298 non-null   object
 1   id                    1298 non-null   int64
 2   author_id             1298 non-null   int64
 3   possibly_sensitive    1298 non-null   bool
 4   reply_settings        1298 non-null   object
 5   created_at            1298 non-null   object
 6   conversation_id       1298 non-null   int64
 7   public_metrics        1298 non-null   object
 8   referenced_tweets     1118 non-null   object
 9   entities              1260 non-null   object
 10  lang                  1298 non-null   object
 11  text                  1298 non-null   object
 12  context_annotations   460 non-null    object
 13  in_reply_to_user_id   201 non-null    float64
 14  attachments           150 non-null    object
 15  geo                   1 non-null      object
 16  metric_retweet_count  1298 non-null   int64
 17  metric_reply_count    1298 non-null   int64
 18  metric_like_count     1298 non-null   int64
 19  metric_quote_count    1298 non-null   int64
dtypes: bool(1), float64(1), int64(7), object(11)
memory usage: 194.1+ KB

In [7]:
# Only take a look at the columns of your dataframe
tweets.columns

Index(['source', 'id', 'author_id', 'possibly_sensitive', 'reply_settings',
       'created_at', 'conversation_id', 'public_metrics', 'referenced_tweets',
       'entities', 'lang', 'text', 'context_annotations',
       'in_reply_to_user_id', 'attachments', 'geo', 'metric_retweet_count',
       'metric_reply_count', 'metric_like_count', 'metric_quote_count'],
      dtype='object')

In [14]:
# Get a sum of all missing values (compare to .info() Non-Null Count?)
tweets.isna()

,source,id,author_id,possibly_sensitive,reply_settings,created_at,conversation_id,public_metrics,referenced_tweets,entities,lang,text,context_annotations,in_reply_to_user_id,attachments,geo,metric_retweet_count,metric_reply_count,metric_like_count,metric_quote_count
0,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False,True,True,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,False,False,False,False
1294,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False
1295,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,False,False,False,False
1296,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,False,False,False,False
1297,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False

In [11]:
# Just get the datatypes
tweets.dtypes

source                   object
id                        int64
author_id                 int64
possibly_sensitive         bool
reply_settings           object
created_at               object
conversation_id           int64
public_metrics           object
referenced_tweets        object
entities                 object
lang                     object
text                     object
context_annotations      object
in_reply_to_user_id     float64
attachments              object
geo                      object
metric_retweet_count      int64
metric_reply_count        int64
metric_like_count         int64
metric_quote_count        int64
dtype: object

In [15]:
# How many rows does my dataframe have?
len(tweets)

1298

***

# Filtering, selecting and renaming

Sometimes the dataset that you are working with contains lots of unncessery data. You will often want to filter (or subset) your dataset to include only: 
* some rows
* some columns 
* some values

In [ ]:
#Let's start with dropping some rows since this dataset is quite large for dealing with

In [17]:
len(tweets)

1298

In [21]:
tweets2 = tweets[0:50]

In [20]:
tweets3 = tweets.sample(n=50)

In [22]:
tweets2.head()

,source,id,author_id,possibly_sensitive,reply_settings,created_at,conversation_id,public_metrics,referenced_tweets,entities,lang,text,context_annotations,in_reply_to_user_id,attachments,geo,metric_retweet_count,metric_reply_count,metric_like_count,metric_quote_count
0,Twitter for Android,1496434995132575748,1495746927794835457,False,everyone,2022-02-23T10:41:19.000Z,1496434995132575748,"{'retweet_count': 208, 'reply_count': 0, 'like...","[{'type': 'retweeted', 'id': '1489536434054868...","{'mentions': [{'start': 3, 'end': 18, 'usernam...",pt,RT @tatuadoysafado: Gravei meu primeiro conteu...,NaN,NaN,NaN,NaN,208,0,0,0
1,Twitter Web App,1496434990413975557,130796328,False,everyone,2022-02-23T10:41:18.000Z,1496434990413975557,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",NaN,"{'urls': [{'start': 245, 'end': 268, 'url': 'h...",it,Conservazione sostitutiva e messa a norma in a...,"[{'domain': {'id': '66', 'name': 'Interests an...",NaN,NaN,NaN,0,0,0,0
2,Twitter for Android,1496434987666755588,873649157185171467,False,everyone,2022-02-23T10:41:18.000Z,1496434987666755588,"{'retweet_count': 2011, 'reply_count': 0, 'lik...","[{'type': 'retweeted', 'id': '1496205931553730...","{'mentions': [{'start': 3, 'end': 18, 'usernam...",en,RT @Mindfulness_DQ: More prayer. More self-car...,"[{'domain': {'id': '65', 'name': 'Interests an...",NaN,NaN,NaN,2011,0,0,0
3,Twitter for iPhone,1496434984332275715,4405550069,False,everyone,2022-02-23T10:41:17.000Z,1496434984332275715,"{'retweet_count': 4, 'reply_count': 0, 'like_c...","[{'type': 'retweeted', 'id': '1496131686106599...","{'mentions': [{'start': 3, 'end': 13, 'usernam...",en,RT @TechHerNG: Google is rethinking its privac...,"[{'domain': {'id': '46', 'name': 'Brand Catego...",NaN,NaN,NaN,4,0,0,0
4,Twitter for Android,1496434984076419074,849164739880001536,False,everyone,2022-02-23T10:41:17.000Z,1496434984076419074,"{'retweet_count': 64, 'reply_count': 0, 'like_...","[{'type': 'retweeted', 'id': '1496332436799737...","{'mentions': [{'start': 3, 'end': 17, 'usernam...",en,RT @odisha_police: OTP is not only stand for t...,"[{'domain': {'id': '65', 'name': 'Interests an...",NaN,NaN,NaN,64,0,0,0

In [23]:
tweets3.head()

,source,id,author_id,possibly_sensitive,reply_settings,created_at,conversation_id,public_metrics,referenced_tweets,entities,lang,text,context_annotations,in_reply_to_user_id,attachments,geo,metric_retweet_count,metric_reply_count,metric_like_count,metric_quote_count
666,Twitter for iPhone,1496429200710025217,1649630060,False,everyone,2022-02-23T10:18:18.000Z,1475754575298588675,"{'retweet_count': 0, 'reply_count': 0, 'like_c...","[{'type': 'replied_to', 'id': '149642914706484...","{'mentions': [{'start': 0, 'end': 13, 'usernam...",en,@Mska30531143 We at Trust Wallet believe in pr...,NaN,1.481962e+18,NaN,NaN,0,0,0,0
422,Twitter Web App,1496431533028261890,1426087615128817666,False,everyone,2022-02-23T10:27:34.000Z,1496431533028261890,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",NaN,"{'hashtags': [{'start': 31, 'end': 39, 'tag': ...",en,Requesting $ONE funds from the #Stakely Faucet...,"[{'domain': {'id': '46', 'name': 'Brand Catego...",NaN,NaN,NaN,0,0,0,0
677,Twitter for iPhone,1496429120028397568,1485026372879851532,False,everyone,2022-02-23T10:17:59.000Z,1496429120028397568,"{'retweet_count': 568, 'reply_count': 0, 'like...","[{'type': 'retweeted', 'id': '1487166940544122...","{'mentions': [{'start': 3, 'end': 16, 'usernam...",en,RT @dothaitian02: picking up my very hot frien...,NaN,NaN,NaN,NaN,568,0,0,0
1254,Twitter for Android,1496425313009602567,1429987193049784322,False,everyone,2022-02-23T10:02:51.000Z,1496425313009602567,"{'retweet_count': 10, 'reply_count': 0, 'like_...","[{'type': 'retweeted', 'id': '1496072947131641...","{'mentions': [{'start': 3, 'end': 17, 'usernam...",en,RT @Suthanai20682: #EARNITAct is a hate crime ...,"[{'domain': {'id': '88', 'name': 'Political Bo...",NaN,NaN,NaN,10,0,0,0
144,Twitter for iPhone,1496433728305958913,1184049087752089600,False,everyone,2022-02-23T10:36:17.000Z,1496433728305958913,"{'retweet_count': 2, 'reply_count': 0, 'like_c...","[{'type': 'retweeted', 'id': '1496419942773796...","{'mentions': [{'start': 3, 'end': 19, 'usernam...",en,RT @VisualsByTHOLLU: Privacy is power. What pe...,NaN,NaN,NaN,NaN,2,0,0,0

In [ ]:
#Sometimes we want to drop certain column because we will not need them
#Notice the inplace approach to dropping columns in the book. Inplace can come in handy in many cases

In [30]:
#We can alterntively choose which columns to keep
#Note that there are two [[ ]] for this. Do you understand why? 
tweets[['source', 'id', 'author_id', 'possibly_sensitive', 'reply_settings',
       'created_at', 'conversation_id']]

,source,id,author_id,possibly_sensitive,reply_settings,created_at,conversation_id
0,Twitter for Android,1496434995132575748,1495746927794835457,False,everyone,2022-02-23T10:41:19.000Z,1496434995132575748
1,Twitter Web App,1496434990413975557,130796328,False,everyone,2022-02-23T10:41:18.000Z,1496434990413975557
2,Twitter for Android,1496434987666755588,873649157185171467,False,everyone,2022-02-23T10:41:18.000Z,1496434987666755588
3,Twitter for iPhone,1496434984332275715,4405550069,False,everyone,2022-02-23T10:41:17.000Z,1496434984332275715
4,Twitter for Android,1496434984076419074,849164739880001536,False,everyone,2022-02-23T10:41:17.000Z,1496434984076419074
...,...,...,...,...,...,...,...
1293,Twitter for iPhone,1496424970951569409,56481748,False,everyone,2022-02-23T10:01:29.000Z,1496424970951569409
1294,TweetDeck,1496424969932541952,1290842099244363776,False,everyone,2022-02-23T10:01:29.000Z,1496424775149035528
1295,Twitter for iPhone,1496424961640128512,1215284173939802112,True,everyone,2022-02-23T10:01:27.000Z,1496424961640128512
1296,Twitter for iPhone,1496424961145458691,1172726522446114816,False,everyone,2022-02-23T10:01:27.000Z,1496424961145458691
1297,Twitter for Android,1496424957420896257,56672287,False,everyone,2022-02-23T10:01:26.000Z,1496378171641454592

In [ ]:
tweets.head()

In [34]:
#Sometimes we may only want to keep rows with certain values 
tweets_long = tweets[tweets['text'].str.len() == 50]

len(tweets)

1298

In [35]:
len(tweets_long)

0

In [ ]:
#Renaming columns 

tweets.rename({'oldname':'newname'})

In [36]:
tweets.dtypes

source                   object
id                        int64
author_id                 int64
possibly_sensitive         bool
reply_settings           object
created_at               object
conversation_id           int64
public_metrics           object
referenced_tweets        object
entities                 object
lang                     object
text                     object
context_annotations      object
in_reply_to_user_id     float64
attachments              object
geo                      object
metric_retweet_count      int64
metric_reply_count        int64
metric_like_count         int64
metric_quote_count        int64
dtype: object

In [37]:
#Changing data type of a column
tweets['metric_retweet_count'] = tweets['metric_retweet_count'].astype(str)

In [38]:
tweets.dtypes

source                   object
id                        int64
author_id                 int64
possibly_sensitive         bool
reply_settings           object
created_at               object
conversation_id           int64
public_metrics           object
referenced_tweets        object
entities                 object
lang                     object
text                     object
context_annotations      object
in_reply_to_user_id     float64
attachments              object
geo                      object
metric_retweet_count     object
metric_reply_count        int64
metric_like_count         int64
metric_quote_count        int64
dtype: object

In [39]:
#applying function to a column
#function that divides by 10

def devideby10(count):
    return count/10

In [40]:
devideby10(50)

5.0

In [41]:
tweets['by10'] = tweets['metric_reply_count'].apply(devideby10)

In [42]:
tweets.head()

,source,id,author_id,possibly_sensitive,reply_settings,created_at,conversation_id,public_metrics,referenced_tweets,entities,...,text,context_annotations,in_reply_to_user_id,attachments,geo,metric_retweet_count,metric_reply_count,metric_like_count,metric_quote_count,by10
0,Twitter for Android,1496434995132575748,1495746927794835457,False,everyone,2022-02-23T10:41:19.000Z,1496434995132575748,"{'retweet_count': 208, 'reply_count': 0, 'like...","[{'type': 'retweeted', 'id': '1489536434054868...","{'mentions': [{'start': 3, 'end': 18, 'usernam...",...,RT @tatuadoysafado: Gravei meu primeiro conteu...,NaN,NaN,NaN,NaN,208,0,0,0,0.0
1,Twitter Web App,1496434990413975557,130796328,False,everyone,2022-02-23T10:41:18.000Z,1496434990413975557,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",NaN,"{'urls': [{'start': 245, 'end': 268, 'url': 'h...",...,Conservazione sostitutiva e messa a norma in a...,"[{'domain': {'id': '66', 'name': 'Interests an...",NaN,NaN,NaN,0,0,0,0,0.0
2,Twitter for Android,1496434987666755588,873649157185171467,False,everyone,2022-02-23T10:41:18.000Z,1496434987666755588,"{'retweet_count': 2011, 'reply_count': 0, 'lik...","[{'type': 'retweeted', 'id': '1496205931553730...","{'mentions': [{'start': 3, 'end': 18, 'usernam...",...,RT @Mindfulness_DQ: More prayer. More self-car...,"[{'domain': {'id': '65', 'name': 'Interests an...",NaN,NaN,NaN,2011,0,0,0,0.0
3,Twitter for iPhone,1496434984332275715,4405550069,False,everyone,2022-02-23T10:41:17.000Z,1496434984332275715,"{'retweet_count': 4, 'reply_count': 0, 'like_c...","[{'type': 'retweeted', 'id': '1496131686106599...","{'mentions': [{'start': 3, 'end': 13, 'usernam...",...,RT @TechHerNG: Google is rethinking its privac...,"[{'domain': {'id': '46', 'name': 'Brand Catego...",NaN,NaN,NaN,4,0,0,0,0.0
4,Twitter for Android,1496434984076419074,849164739880001536,False,everyone,2022-02-23T10:41:17.000Z,1496434984076419074,"{'retweet_count': 64, 'reply_count': 0, 'like_...","[{'type': 'retweeted', 'id': '1496332436799737...","{'mentions': [{'start': 3, 'end': 17, 'usernam...",...,RT @odisha_police: OTP is not only stand for t...,"[{'domain': {'id': '65', 'name': 'Interests an...",NaN,NaN,NaN,64,0,0,0,0.0

In [43]:
tweets['by10'].value_counts()

by10
0.0    1230
0.1      62
0.2       4
0.4       2
Name: count, dtype: int64

In [44]:
tweets['metric_reply_count'].value_counts()

metric_reply_count
0    1230
1      62
2       4
4       2
Name: count, dtype: int64

# Merging

In [45]:
tweets

,source,id,author_id,possibly_sensitive,reply_settings,created_at,conversation_id,public_metrics,referenced_tweets,entities,...,text,context_annotations,in_reply_to_user_id,attachments,geo,metric_retweet_count,metric_reply_count,metric_like_count,metric_quote_count,by10
0,Twitter for Android,1496434995132575748,1495746927794835457,False,everyone,2022-02-23T10:41:19.000Z,1496434995132575748,"{'retweet_count': 208, 'reply_count': 0, 'like...","[{'type': 'retweeted', 'id': '1489536434054868...","{'mentions': [{'start': 3, 'end': 18, 'usernam...",...,RT @tatuadoysafado: Gravei meu primeiro conteu...,NaN,NaN,NaN,NaN,208,0,0,0,0.0
1,Twitter Web App,1496434990413975557,130796328,False,everyone,2022-02-23T10:41:18.000Z,1496434990413975557,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",NaN,"{'urls': [{'start': 245, 'end': 268, 'url': 'h...",...,Conservazione sostitutiva e messa a norma in a...,"[{'domain': {'id': '66', 'name': 'Interests an...",NaN,NaN,NaN,0,0,0,0,0.0
2,Twitter for Android,1496434987666755588,873649157185171467,False,everyone,2022-02-23T10:41:18.000Z,1496434987666755588,"{'retweet_count': 2011, 'reply_count': 0, 'lik...","[{'type': 'retweeted', 'id': '1496205931553730...","{'mentions': [{'start': 3, 'end': 18, 'usernam...",...,RT @Mindfulness_DQ: More prayer. More self-car...,"[{'domain': {'id': '65', 'name': 'Interests an...",NaN,NaN,NaN,2011,0,0,0,0.0
3,Twitter for iPhone,1496434984332275715,4405550069,False,everyone,2022-02-23T10:41:17.000Z,1496434984332275715,"{'retweet_count': 4, 'reply_count': 0, 'like_c...","[{'type': 'retweeted', 'id': '1496131686106599...","{'mentions': [{'start': 3, 'end': 13, 'usernam...",...,RT @TechHerNG: Google is rethinking its privac...,"[{'domain': {'id': '46', 'name': 'Brand Catego...",NaN,NaN,NaN,4,0,0,0,0.0
4,Twitter for Android,1496434984076419074,849164739880001536,False,everyone,2022-02-23T10:41:17.000Z,1496434984076419074,"{'retweet_count': 64, 'reply_count': 0, 'like_...","[{'type': 'retweeted', 'id': '1496332436799737...","{'mentions': [{'start': 3, 'end': 17, 'usernam...",...,RT @odisha_police: OTP is not only stand for t...,"[{'domain': {'id': '65', 'name': 'Interests an...",NaN,NaN,NaN,64,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293,Twitter for iPhone,1496424970951569409,56481748,False,everyone,2022-02-23T10:01:29.000Z,1496424970951569409,"{'retweet_count': 2639, 'reply_count': 0, 'lik...","[{'type': 'retweeted', 'id': '1496145104880521...","{'mentions': [{'start': 3, 'end': 16, 'usernam...",...,"RT @WealthInc247: Fall in love with privacy, b...",NaN,NaN,NaN,NaN,2639,0,0,0,0.0
1294,TweetDeck,1496424969932541952,1290842099244363776,False,everyone,2022-02-23T10:01:29.000Z,1496424775149035528,"{'retweet_count': 1, 'reply_count': 1, 'like_c...","[{'type': 'replied_to', 'id': '149642477514903...","{'hashtags': [{'start': 144, 'end': 159, 'tag'...",...,The bill contains dangerous provisions such as...,"[{'domain': {'id': '65', 'name': 'Interests an...",1.290842e+18,NaN,NaN,1,1,1,0,0.1
1295,Twitter for iPhone,1496424961640128512,1215284173939802112,True,everyone,2022-02-23T10:01:27.000Z,1496424961640128512,"{'retweet_count': 292, 'reply_count': 0, 'like...","[{'type': 'retweeted', 'id': '1495759215054442...","{'urls': [{'start': 87, 'end': 110, 'url': 'ht...",...,RT @oteuporrete23: Vou mostrar os dias que che...,NaN,NaN,NaN,NaN,292,0,0,0,0.0
1296,Twitter for iPhone,1496424961145458691,1172726522446114816,False,everyone,2022-02-23T10:01:27.000Z,1496424961145458691,"{'retweet_count': 19, 'reply_count': 0, 'like_...","[{'type': 'retweeted', 'id': '1496414956426002...","{'mentions': [{'start': 3, 'end': 18, 'usernam...",...,RT @everyoneswhore: She just wants some privac...,NaN,NaN,NaN,NaN,19,0,0,0,0.0
1297,Twitter for Android,1496424957420896257,56672287,False,everyone,2022-02-23T10:01:26.000Z,1496378171641454592,"{'retweet_count': 0, 'reply_count': 0, 'like_c...","[{'type': 'replied_to', 'id': '149637817164145...","{'mentions': [{'start': 0, 'end': 13, 'usernam...",...,@virtuexmoir2 Settigns and Privacy &gt; Securi...,"[{'domain': {'id': '65', 'name': 'Interests an...",1.294110e+18,NaN,NaN,0,0,0,0,0.0

In [46]:
users = pd.read_csv("users.csv")

In [47]:
users

,pinned_tweet_id,description,created_at,profile_image_url,name,username,id,verified,public_metrics,url,protected,entities,location,metric_followers_count,metric_following_count,metric_tweet_count,metric_listed_count
0,1.496033e+18,+18 \nSó putaria,2022-02-21T13:07:22.000Z,https://pbs.twimg.com/profile_images/149574728...,Thi,Thirolagrossa,1495746927794835457,False,"{'followers_count': 33, 'following_count': 304...",NaN,False,NaN,NaN,33,304,120,0
1,1.489536e+18,novinho fetichista exibicionista e sem pudor🔞,2021-12-08T01:52:23.000Z,https://pbs.twimg.com/profile_images/149035957...,Jhonny,tatuadoysafado,1468397897645543427,False,"{'followers_count': 3196, 'following_count': 2...",NaN,False,NaN,NaN,3196,202,42,2
2,1.454427e+18,My fetish world 😈| Privacy: https://t.co/SM0kY...,2021-10-27T16:52:10.000Z,https://pbs.twimg.com/profile_images/145897921...,Henri Dot 🍁💦,henridotado,1453404081574273033,False,"{'followers_count': 45007, 'following_count': ...",NaN,False,"{'description': {'urls': [{'start': 28, 'end':...",NaN,45007,616,320,180
3,NaN,dirittodellinformatica.it è la rivista telemat...,2010-04-08T10:13:08.000Z,https://pbs.twimg.com/profile_images/144894006...,Diritto dell'Informatica,hitechlaw,130796328,False,"{'followers_count': 454, 'following_count': 2,...",https://t.co/PsQoduCosO,False,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",Bologna,454,2,130,9
4,1.437984e+18,"Nouran is my real name, mais je suis Néfertiti...",2017-06-10T21:12:45.000Z,https://pbs.twimg.com/profile_images/144464638...,Nefertiti,cleopatrabbg,873649157185171467,False,"{'followers_count': 282, 'following_count': 12...",NaN,False,NaN,La Vie En Rose,282,1289,4920,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1706,NaN,The UP Internet Freedom Network (UP INTERNET) ...,2020-08-05T02:48:44.000Z,https://pbs.twimg.com/profile_images/129084233...,UP Internet Freedom Network,upinter_net,1290842099244363776,False,"{'followers_count': 203, 'following_count': 71...",https://t.co/uR7sL6sHmj,False,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",NaN,203,71,333,3
1707,1.443327e+18,Reserve account 👉 @jackson_clark4,2020-01-09T14:48:30.000Z,https://pbs.twimg.com/profile_images/148424353...,Jackson_clark 130K,jackson_clark12,1215284173939802112,False,"{'followers_count': 133727, 'following_count':...",https://t.co/MSFrtDwZrY,False,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",İstanbul,133727,514,30155,296
1708,1.240317e+18,"functions at 2pm, currently on autopilot",2019-09-14T04:19:36.000Z,https://pbs.twimg.com/profile_images/145484437...,kape,thesadfangay,1172726522446114816,False,"{'followers_count': 200, 'following_count': 33...",NaN,False,NaN,in between trials and success,200,331,169034,0
1709,1.495391e+18,My life is a joke and I'm not laughing anymore.,2009-07-14T11:44:29.000Z,https://pbs.twimg.com/profile_images/941825252...,TheSuperKim,TheSuperKim,56672287,False,"{'followers_count': 420, 'following_count': 41...",NaN,False,NaN,NaN,420,418,48041,4
1710,1.491647e+18,"marina, c'mon drop the non mickey mouse versio...",2020-08-14T03:12:24.000Z,https://pbs.twimg.com/profile_images/148945929...,a | stuck in vm pyeongchang era,virtuexmoir2,1294109558093291520,False,"{'followers_count': 545, 'following_count': 93...",https://t.co/7hOQNeoXhS,False,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",she/her,545,932,10041,5

In [48]:
len(tweets), len(users)

(1298, 1711)

In [50]:
#Merging on different keys - left
merge_l = users.merge(tweets, how = 'left', right_on='author_id', left_on = 'id')
len(merge_l)

1963

In [51]:
merge_l.isna().sum()

pinned_tweet_id           1006
description                291
created_at_x                 0
profile_image_url            0
name                         0
username                     0
id_x                         0
verified                     0
public_metrics_x             0
url                       1141
protected                    0
entities_x                 892
location                   809
metric_followers_count       0
metric_following_count       0
metric_tweet_count           0
metric_listed_count          0
source                     665
id_y                       665
author_id                  665
possibly_sensitive         665
reply_settings             665
created_at_y               665
conversation_id            665
public_metrics_y           665
referenced_tweets          845
entities_y                 703
lang                       665
text                       665
context_annotations       1503
in_reply_to_user_id       1762
attachments               1813
geo                       1962
metric_retweet_count       665
metric_reply_count         665
metric_like_count          665
metric_quote_count         665
by10                       665
dtype: int64

In [52]:
#Merging on different keys - right
merge_r = users.merge(tweets, how = 'right', right_on='author_id', left_on = 'id')
len(merge_r)

1298

In [53]:
merge_l.isna().sum()

pinned_tweet_id           1006
description                291
created_at_x                 0
profile_image_url            0
name                         0
username                     0
id_x                         0
verified                     0
public_metrics_x             0
url                       1141
protected                    0
entities_x                 892
location                   809
metric_followers_count       0
metric_following_count       0
metric_tweet_count           0
metric_listed_count          0
source                     665
id_y                       665
author_id                  665
possibly_sensitive         665
reply_settings             665
created_at_y               665
conversation_id            665
public_metrics_y           665
referenced_tweets          845
entities_y                 703
lang                       665
text                       665
context_annotations       1503
in_reply_to_user_id       1762
attachments               1813
geo                       1962
metric_retweet_count       665
metric_reply_count         665
metric_like_count          665
metric_quote_count         665
by10                       665
dtype: int64

In [ ]:
#Merging on different keys - outer
merge_o = users.merge(tweets, how = 'outer', right_on='author_id', left_on = 'id')
len(merge_o)

In [49]:
#Merging on different keys - inner
merge_i = users.merge(tweets, how = 'inner', right_on='author_id', left_on = 'id')
len(merge_i)

1298

In [ ]:
#Concatenating 
apple_3 = pd.read_csv("apple_3.csv", sep=';')
apple_4 = pd.read_csv("apple_4.csv", sep=';')

full = pd.concat([apple_3, apple_4])
len(apple_3)

In [ ]:
len(apple_4)

In [ ]:
#len(full) = len(apple_3) + (apple_4)
len(full)